services:
  f1-api:
    image: ghcr.io/philipwoulfe/f1competition:${TAG:-latest} # Or :feat-branch-name
    container_name: ${CONTINER_NAME:-f1-test}
    ports:
      - "${HOST_PORT:-5000}:8080"
    restart: unless-stopped

  # The Butler: Automatically pulls new images from GitHub
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # This line allows Watchtower to use your existing 'docker login' credentials
      - /root/.docker/config.json:/config.json
    command: --interval 30 --cleanup # Checks every 30 seconds and deletes old images
    restart: unless-stopped