services:
  f1-api:
    build:
      context: .
      dockerfile: src/F1.Api/Dockerfile.debug
    ports:
      - "5000:8080"
      - "15000:15000"
    volumes:
      - .:/app
    # Now this will actually run because we removed the Entrypoint in the Dockerfile
    command: ["dotnet", "watch", "run", "--project", "src/F1.Api/F1.Api.csproj", "--urls", "http://0.0.0.0:8080"]
    tty: true